name: GCP Python 3.7.14
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.14
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.14
    - name: Install dependencies
      run: |
        make install-gcp
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
    - name: Format code with Python Black
      run: |
        make format
