name: Azure Python 3.10.6
on: [push, pull_request]

jobs:
  python-setup:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.6
      - name: Install dependencies
        run: |
          make install
      - name: Format code with Python Black
        run: |
          make format
      - name: Lint
        run: |
          make lint
      - name: Test
        run: |
          make test
  stale:
      runs-on: ubuntu-latest
      permissions:
        issues: write
        pull-requests: write

      steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 15
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'problema no resuelto por mas de 30 dias'
          stale-pr-message: 'problema se cierra por exceder los dias establecidos'
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
  
